trigger:
- master
jobs:
  - job:
    displayName: macOS-M1
    pool:
      name: Default
      demands:
        - rust
        - agent.os -equals Darwin
    steps:
      - checkout: self
        clean: true
      - script: |
          arch -arm64 cargo -v build 2> >(tee stderr.log >&2)
          CODE=$?
          grep -qe ^warning stderr.log && grep -e ^warning stderr.log | xargs -ILINE echo "##vso[task.logissue type=warning]LINE" || true
          grep -qe ^error stderr.log && grep -e ^error stderr.log | xargs -ILINE echo "##vso[task.logissue type=error]LINE" || true
          exit $CODE
        displayName: Build
      - script: |
          arch -arm64 cargo clippy 2> >(tee stderr.log >&2)
          CODE=$?
          grep -qe ^warning stderr.log && grep -e ^warning stderr.log | xargs -ILINE echo "##vso[task.logissue type=warning]LINE" || true
          grep -qe ^error stderr.log && grep -e ^error stderr.log | xargs -ILINE echo "##vso[task.logissue type=error]LINE" || true
          exit $CODE
        displayName: Clippy
