[github]
host = "https://api.github.com/graphql"

[[oss]]
repo ="bumptech/glide"
version = "v4.6.1"
prerelease = false

[[oss]]
repo = "google/dagger"
version = "2.14.1"
prerelease = false

[[oss]]
repo = "tbroyer/gradle-errorprone-plugin"
version = "v0.0.13"
prerelease = false

[[oss]]
repo = "google/error-prone"
version = "v2.2.0"
prerelease = false

[[oss]]
repo = "square/leakcanary"
version = "v1.5.4"
prerelease = false

[[oss]]
repo = "ReactiveX/RxJava"
version = "2.1.12"
prerelease = false

[[oss]]
repo = "ReactiveX/RxAndroid"
version = "2.0.2"
prerelease = false
